login: &common
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: password
  host: localhost
  port: 5432
  database: test
  min_messages: warning # silence the NOTICE: messages from postgres


development:
  <<: *common

qa:
  <<: *common

stg:
  <<: *common

production:
  <<: *common
  

test:
  <<: *common
  
